# Assignment 2: QSAR Data Curation Using ChEMBL
## Target: Androgen Receptor (CHEMBL1871)

# **Part 1: Data Collection & Curation**
First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.

This allows us to:

*   Save datasets
*   Reload data across sessions
*   Organize project files

In [4]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Now create "data" folder in our "Colab Notebooks" folder on Google Drive.

In [5]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

# **Install and Import Required Libraries**

We install the ChEMBL web service package so that we can retrieve bioactivity data.

In [13]:
!pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.2.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Requirement already satisfied: url-normalize>=1.4 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

# **Import Libraries**
*   pandas for data handling
*   new_client from chembl for accessing the database

In [14]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# **Step 1: Search for Target Protein**
Target Identification (Androgen Receptor)

Search ChEMBL for the Androgen Receptor target and select the most relevant entry.

In [15]:
target = new_client.target
target_query = target.search("Androgen Receptor")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Androgen receptor,24.0,False,CHEMBL1871,"[{'accession': 'P10275', 'component_descriptio...",SINGLE PROTEIN,9606.0
1,[],Homo sapiens,Androgen receptor/Baculoviral IAP repeat-conta...,24.0,False,CHEMBL4296118,"[{'accession': 'P10275', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
2,[],Homo sapiens,Androgen receptor/PELP1,24.0,False,CHEMBL4523653,"[{'accession': 'P10275', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
3,[],Homo sapiens,Protein cereblon/Androgen receptor,24.0,False,CHEMBL4523684,"[{'accession': 'P10275', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
4,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/And...,24.0,False,CHEMBL4523730,"[{'accession': 'P10275', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0

**Retrieve Bioactivity data for selected target.**

In [16]:
selected_target = "CHEMBL1871"
selected_target

'CHEMBL1871'

Now retrieve only bioactivity data for target; **Androgen Receptor(CHEMBL1871) with reported IC 50 values in nM (nanomolar) unit.**

In [20]:
activity = new_client.activity
results = activity.filter(target_chembl_id="CHEMBL1871", standard_type="IC50")
df1 = pd.DataFrame.from_dict(results)
df1.head(5)
df1.standard_type.unique()

array(['IC50'], dtype=object)

Finally Save the resulting bioactivity data to a CSV file bioactivity_raw_data.csv.

In [21]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

Now copy "bioactivity_raw_data.csv" file to Google Drive, in folder "data".

In [22]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [23]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 3132
-rw------- 1 root root 3206508 Jan 23 13:39 bioactivity_raw_data.csv

In [24]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,32669,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-12 to 10e-5 M,B,,,BAO_0000190,BAO_0000357,single protein format,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccsc1)Oc1ccc(F)cc1-3,,,CHEMBL1145087,J Med Chem,2003,"{'bei': '17.12', 'le': '0.33', 'lle': '-0.38', 'sei': '31.36'}",CHEMBL134277,,CHEMBL134277,6.67,0,http://www.openphacts.org/units/Nanomolar,253290,=,1,1,=,,IC50,nM,,215.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,215.0
,,37515,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to human androgen receptor of PC3/AR cell lysate,B,,,BAO_0000190,BAO_0000219,cell-based format,CC1(C)C(=O)N(c2ccc(C#N)c(C(F)(F)F)c2)C(=O)N1CCOCCOCc1ccc(O)c(C(N)=O)c1,,,CHEMBL1145911,J Med Chem,2003,"{'bei': '13.31', 'le': '0.26', 'lle': '3.95', 'sei': '4.87'}",CHEMBL146794,,CHEMBL146794,7.11,0,http://www.openphacts.org/units/Nanomolar,292353,=,1,1,=,,IC50,nM,,77.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,77.0
,,42305,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to human androgen receptor of PC3/AR cell lysate,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3OC1C[C@H](NCNC(=O)c2cc(COCC#CCN3C(=O)N(c4ccc(C#N)c(C(F)(F)F)c4)C(=O)C3(C)C)ccc2O)[C@H](O)[C@H](C)O1,,,CHEMBL1145911,J Med Chem,2003,"{'bei': '6.58', 'le': None, 'lle': None, 'sei': None}",CHEMBL2112885,,CHEMBL2112885,7.05,0,http://www.openphacts.org/units/Nanomolar,292356,=,1,1,=,,IC50,nM,,90.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,90.0
,,45856,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-12 to 10e-5 M,B,,,BAO_0000190,BAO_0000357,single protein format,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1N(C)C)Oc1ccc(F)cc1-3,,,CHEMBL1145087,J Med Chem,2003,"{'bei': '13.65', 'le': '0.25', 'lle': '-1.24', 'sei': '23.77'}",CHEMBL336353,,CHEMBL336353,5.82,0,http://www.openphacts.org/units/Nanomolar,253301,=,1,1,=,,IC50,nM,,1500.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,1500.0
,,47124,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-12 to 10e-5 M,B,,,BAO_0000190,BAO_0000357,single protein format,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1)Oc1c(F)cccc1-3,,,CHEMBL1145087,J Med Chem,2003,"{'bei': '15.77', 'le': '0.28', 'lle': '-0.94', 'sei': '28.44'}",CHEMBL413309,,CHEMBL413309,6.05,0,http://www.openphacts.org/units/Nanomolar,253313,=,1,1,=,,IC50,nM,,900.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,900.0
,,47135,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to human androgen receptor of PC3/AR cell lysate,B,,,BAO_0000190,BAO_0000219,cell-based format,NC(=O)c1ccccc1O,,,CHEMBL1145911,J Med Chem,2003,,CHEMBL27577,SALICYLAMIDE,CHEMBL27577,,0,http://www.openphacts.org/units/Nanomolar,292357,>,1,1,>,,IC50,nM,,1000.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,1000.0
,,48440,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-12 to 10e-5 M,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)O[C@]1(C(C)=O)CC[C@H]2[C@@H]3C[C@H](C)C4=CC(=O)CC[C@]4(C)[C@H]3CC[C@@]21C,,,CHEMBL1145087,J Med Chem,2003,"{'bei': '21.25', 'le': '0.40', 'lle': '3.55', 'sei': '13.59'}",CHEMBL717,MEDROXYPROGESTERONE ACETATE,CHEMBL717,8.21,1,http://www.openphacts.org/units/Nanomolar,253311,=,1,1,=,,IC50,nM,,6.1,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,6.1
,,49825,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to human androgen receptor of PC3/AR cell lysate,B,,,BAO_0000190,BAO_0000219,cell-based format,CC1(C)C(=O)N(c2ccc(C#N)c(C(F)(F)F)c2)C(=O)N1CCOCCOCCOCc1ccc(O)c(C(N)=O)c1,,,CHEMBL1145911,J Med Chem,2003,"{'bei': '11.20', 'le': '0.22', 'lle': '3.30', 'sei': '4.17'}",CHEMBL348495,,CHEMBL348495,6.48,0,http://www.openphacts.org/units/Nanomolar,292354,=,1,1,=,,IC50,nM,,332.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,332.0
,,49827,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to human androgen receptor of PC3/AR cell lysate,B,,,BAO_0000190,BAO_0000219,cell-based format,CC1(C)C(=O)N(c2ccc(C#N)c(C(F)(F)F)c2)C(=O)N1CCOCCN1CCN(CCOCc2ccc(O)c(C(N)=O)c2)CC1,,,CHEMBL1145911,J Med Chem,2003,"{'bei': '9.99', 'le': '0.19', 'lle': '3.68', 'sei': '4.23'}",CHEMBL347556,,CHEMBL347556,6.46,0,http://www.openphacts.org/units/Nanomolar,292359,=,1,1,=,,IC50,nM,,346.0,CHEMBL1871,Homo sapiens,Androgen receptor,9606,,,IC50,nM,UO_0000065,,346.0

# **Step 3: Bioactivity Data Retrieval (IC50)**
Retrieve bioactivity data (IC50) for the selected target.

Inspect Missing Values

In [25]:
df1["standard_type"].isna().sum()

np.int64(0)

Filter Rows with Valid Bioactivity Values.

In [27]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32669,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-1...,B,None,None,BAO_0000190,...,Homo sapiens,Androgen receptor,9606,None,None,IC50,nM,UO_0000065,None,215.0
1,None,None,37515,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to...,B,None,None,BAO_0000190,...,Homo sapiens,Androgen receptor,9606,None,None,IC50,nM,UO_0000065,None,77.0
2,None,None,42305,[],CHEMBL647749,Inhibition of 1.0 nM [3H]mibolerone binding to...,B,None,None,BAO_0000190,...,Homo sapiens,Androgen receptor,9606,None,None,IC50,nM,UO_0000065,None,90.0
3,None,None,45856,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-1...,B,None,None,BAO_0000190,...,Homo sapiens,Androgen receptor,9606,None,None,IC50,nM,UO_0000065,None,1500.0
4,None,None,47124,[],CHEMBL647746,Inhibition of human androgen receptor at 10e-1...,B,None,None,BAO_0000190,...,Homo sapiens,Androgen receptor,9606,None,None,IC50,nM,UO_0000065,None,900.0

## **Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [29]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [30]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [31]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [32]:
df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL134277,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccsc1)Oc1ccc(...,215.0,active
1,CHEMBL146794,CC1(C)C(=O)N(c2ccc(C#N)c(C(F)(F)F)c2)C(=O)N1CC...,77.0,active
2,CHEMBL2112885,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,90.0,active
3,CHEMBL336353,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1N(C)C)O...,1500.0,intermediate
4,CHEMBL413309,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1)Oc1c(F...,900.0,active

Remove Compounds without Valid SMILES. Drop rows with NaN, empty or None SMILES values.

In [33]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL134277,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccsc1)Oc1ccc(...,215.0,active
1,CHEMBL146794,CC1(C)C(=O)N(c2ccc(C#N)c(C(F)(F)F)c2)C(=O)N1CC...,77.0,active
2,CHEMBL2112885,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,90.0,active
3,CHEMBL336353,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1N(C)C)O...,1500.0,intermediate
4,CHEMBL413309,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1)Oc1c(F...,900.0,active

Save Preprocessed Bioactivity Data. Save the cleaned dataset to CSV and copy to Google Drive.

In [34]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_preprocessed_data.csv  bioactivity_raw_data.csv

# **End of Part 1: Data Collection and Curation**.